### ISSUE TITLE
Status unknown

### ISSUE THREAD

**Issue by Druidblack** [arnesacnussem/jellyfin-plugin-meilisearch#5]
Good afternoon. After another reboot of jf. The plugin shows the unknown status.  The refresh button does not help.

The plugin works at the same time. Is there anything that can be done to ensure that the status is always displayed correctly?

**Comment by Fabian1601** [comment]
Hello,
which version of jellyfin are you using?
I have jf 10.10.3 and I can also see the queries in Meilisearch, but nothing is faster in the search. 
It is just as slow as without the plugin.
However, the status of the plugin has never been “OK” for me.
Greetings

**Comment by Druidblack** [comment]
Good afternoon. I also use jf 10.10.3. I have several instances of jf. And I use this plugin on all of them.  In all use cases, I see queries in the meilisearch logs and the search has started to work faster. I have a library of 3,600 films, 62,000 episodes (16212 TV series) and 323861 songs. The difference in the search became immediately visible.

**Comment by Fabian1601** [comment]
Hello,
Yes, I can see all the entries in meilisearch and as you said, the search is almost instant. 
In jf, however, it sometimes takes up to 10 seconds. 
Which key did you use for the plugin? The admin key?

**Comment by Druidblack** [comment]
yes

**Comment by arnesacnussem** [comment]
Sorry for late replay, but I cant reproduce the `unknown` status while it working, the `unknown` is the default placeholder when status not loaded from `/meilisearch/status` endpoint, maybe you can check if your browser dev tool's "Network" tab to see if any clue

**Comment by Druidblack** [comment]
I found the reason why the plugin does not show the status. There is a conflict when working with the InPlayerEpisodePreview  https://github.com/Namo2/InPlayerEpisodePreviewplugin. When I turn it off, the status is displayed correctly.

**Comment by arnesacnussem** [comment]
Their code there ([Namo2/InPlayerEpisodePreview/DataFetcher.ts#L14](https://github.com/Namo2/InPlayerEpisodePreview/blob/4eba9531f6b6fd9a61b36a66d1f8aa148060e582/Namo.Plugin.InPlayerEpisodePreview/Web/Services/DataFetcher.ts#L14)) replaced `window.fetch` and caused some side effect, maybe you can open a issue there.
i'll see if i can find a workaround as for now.

```
Request failed to /meilisearch/status TypeError: Failed to construct 'URL': Invalid URL
```
```
VM846:80 TypeError: Failed to construct 'URL': Invalid URL
    at DataFetcher.<anonymous> (DataFetcher.ts:25:28)
    at Generator.next (<anonymous>)
    at fulfilled (AuthService.ts:23:2)
```

**Comment by arnesacnussem** [comment]
I choose to write this simple workaround because idk if `ApiClient.get` do more than just call `fetch`, this is included in release `1.10.1.1`

**Comment by Druidblack** [comment]
After updating the plugin, the status appeared. Thank you for promptly solving the problem from someone else's plugin.
