### ISSUE TITLE
Meilisearch index fails : Guid should contain 32 digits with 4 dashes

### ISSUE THREAD

**Issue by ShakeSp33r** [arnesacnussem/jellyfin-plugin-meilisearch#6]
Scheduled task fail after 0 seconds.

Error : Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

Jellyfin : 10.10.3
Plugin: 1.10.0.0

`[10:38:53] [INF] [16] Jellyfin.Plugin.Meilisearch.ScheduledTask: Executing meilisearch index task
[10:38:53] [INF] [16] Jellyfin.Plugin.Meilisearch.DbIndexer: Indexing items from database: /config/data/data/library.db
[10:38:53] [ERR] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(ParseFailure failureKind)
   at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at Microsoft.Data.Sqlite.SqliteValueReader.GetGuid(Int32 ordinal)
   at Jellyfin.Plugin.Meilisearch.DbIndexer.IndexInternal(MeilisearchClient meilisearch, Index index) in /home/runner/work/jellyfin-plugin-meilisearch/jellyfin-plugin-meilisearch/src/DbIndexer.cs:line 62
   at Jellyfin.Plugin.Meilisearch.DbIndexer.IndexInternal(MeilisearchClient meilisearch, Index index) in /home/runner/work/jellyfin-plugin-meilisearch/jellyfin-plugin-meilisearch/src/DbIndexer.cs:line 97
   at Jellyfin.Plugin.Meilisearch.DbIndexer.IndexInternal(MeilisearchClient meilisearch, Index index) in /home/runner/work/jellyfin-plugin-meilisearch/jellyfin-plugin-meilisearch/src/DbIndexer.cs:line 97
   at Jellyfin.Plugin.Meilisearch.DbIndexer.IndexInternal(MeilisearchClient meilisearch, Index index) in /home/runner/work/jellyfin-plugin-meilisearch/jellyfin-plugin-meilisearch/src/DbIndexer.cs:line 97
   at Jellyfin.Plugin.Meilisearch.Indexer.Index() in /home/runner/work/jellyfin-plugin-meilisearch/jellyfin-plugin-meilisearch/src/Indexer.cs:line 21
   at Jellyfin.Plugin.Meilisearch.ScheduledTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken) in /home/runner/work/jellyfin-plugin-meilisearch/jellyfin-plugin-meilisearch/src/ScheduledTask.cs:line 11
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[10:38:53] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Meilisearch index for all documents Failed after 0 minute(s) and 0 seconds
`

**Comment by ShakeSp33r** [comment]
Please ignore - corrupt record in TypedBaseItems
